# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtWidgets import QVBoxLayout
from scapy.all import *
from netifaces import interfaces
import winreg as wr
import time
import threading
import matplotlib

matplotlib.use('QTAgg')
from select_interface import *
# from select_interface import *
from PyQt5 import QtWidgets
import sys
from PyQt5 import QtCore
from PyQt5.QtWidgets import QApplication, QVBoxLayout, QFileDialog
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg
import matplotlib.pyplot as plt
from MainWindow_UI import *

plt.rcParams['font.sans-serif'] = ['SimHei']  # 显示中文标签
plt.rcParams['axes.unicode_minus'] = False


class Ui_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("网卡选择")
        Dialog.resize(1106, 766)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_select = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select.setGeometry(QtCore.QRect(130, 30, 251, 31))
        self.comboBox_select.setObjectName("comboBox_select")
        self.groupBox_show = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_show.setGeometry(QtCore.QRect(30, 90, 1041, 611))
        self.groupBox_show.setObjectName("groupBox_show")

        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_show)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 1021, 581))
        self.graphicsView.setObjectName("graphicsView")

        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setGeometry(QtCore.QRect(490, 360, 150, 40))
        self.pushButton_show.setObjectName("pushButton_show")

        self.pushButton_select = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select.setGeometry(QtCore.QRect(410, 30, 93, 31))
        self.pushButton_select.setObjectName("pushButton_select")
        self.label_interface = QtWidgets.QLabel(self.centralwidget)
        self.label_interface.setGeometry(QtCore.QRect(40, 30, 131, 31))
        self.label_interface.setObjectName("label_interface")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(530, 30, 93, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        # Dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        # Dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Dialog)
        self.statusbar.setObjectName("statusbar")
        # Dialog.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(Dialog)
        self.actionopen.setObjectName("actionopen")
        self.menu.addAction(self.actionopen)
        self.menubar.addAction(self.menu.menuAction())

        self.pushButton_select.clicked.connect(Dialog.start_sniff)
        self.pushButton_exit.clicked.connect(Dialog.exit_sniff)
        self.pushButton_show.clicked.connect(Dialog.show_traffic)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("MainWindow", "网卡选择"))
        self.groupBox_show.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_select.setText(_translate("MainWindow", "开始"))
        self.pushButton_show.setText(_translate("MainWindow", "查看网卡各接口流量"))
        self.label_interface.setText(_translate("MainWindow", "选择接口"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "打开pcap"))

